config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'koor', to: 'pages#koor'
  get 'piano', to: 'pages#piano'
  get 'didjeridu', to: 'pages#didjeridu'
  get 'agenda', to: 'pages#agenda'

  resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord
  # self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :naam,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :bericht,   :validate => true
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "terpstra.claudia@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contacts_params)
    if
      @contact.valid?
      @contact.deliver
    else
      render :new
    end
  end


  def contacts_params
    params.require(:contact).permit(:naam, :email, :bericht)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def koor
  end

  def piano
  end

  def didjeridu
  end

  def contact
  end

  def agenda
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <h2>Thanks!</h2>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h2>Contact</h2>
  <div class="contact-information">
    <ul>Jan Terpstra</ul>
    <ul>Pastoor Gillisstraat 114</ul>
    <ul>5121 CG</ul>
    <ul>Rijen</ul>
    <br>
    <ul>+31 6 39777370</ul>
    <ul>info@didjeridu.nl</ul>
  </div>
  <div class="form">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
  <p class="paragraph-bold">Wil je meer information over lessen, dirigeren of wil je mij boeken voor een
  didgeridoo optreden, stuur dan even een berichtje</p>

        <%= simple_form_for @contact, class: 'form-horizontal' do |f| %>
        <%= f.input :naam, :required => true %>
        <%= f.input :email, :required => true %>
        <%= f.input :bericht, :as => :text, :required => false, :input_html => {:rows => 8} %>
        <%= f.submit "Versturen", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>

  <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/agenda.html.erb
<div class="container">
  <div class="agenda-card">
  <h4>U bent van harte welkom bij de volgende concerten:</h4>
  <div class="datum-passed">
    <p class="date">16 september 2017</p>
      <p>o.a. Stedelijk Leerdams Mannenkoor “Zang en Vriendschap” van 20.00 tot 20.20 uur in het Winkelcentrum in Leerdam.
    </p>
    <p class="date">24 september  2017</p>
    <p>Koor ExpresZo en flamencogitarist  Alessio Rooders, Sint Jozefkerk, Oude Molenstraat 8, Oss, 12.00 uur.
    </p>
    <p class="date">6 oktober 2017</p>
    <p>Stedelijk Leerdams Mannenkoor "Zang & Vriendschap" 
    Afscheids Concert van Kupalje uit Minsk, Wit Rusland, Maria kerk, Leerdam, 20.00 uur.
    </p>
  </div>
  <p class="date">21 oktober 2017</p>
  <p>Stedelijk Leerdams Mannenkoor "Zang & Vriendschap", KNZV Mannenkoren concours,
    Haarlem Sint Bavo.
  </p>
  <p class="date">19 november 2017</p>
  <p>Koor ExpresZo, Jubileum Concert, De Koppelinck, Geffen.
  </p>
  <p class="date">20 december 2017</p>
  <p>Dongens Mannenkoor Kerst Concert Kapel vd Zusters Fransicanessen, Dongen, 20.00 uur. Solist Tenor André Cruz.
</p>
<p class="date">21 december 2017</p>
<p>Liederenkring, Kerst Concert, Catharinenberg 19.30-20.30 uur</p>
<p class="date">22 december 2017</p>
<p>Dongens Mannenkoor Kerst Concert Oude Kerk, Dongen, 20.00 uur. Solist Tenor André Cruz.</p>
<p class="date">24 december 2017</p>
<p>Kerstmis Vincentius, Udenhout, De Liederenkring. 20.00-21.30 uur. </p>
  </div>
</div>

app/views/pages/didjeridu.html.erb
<div class="container hidden-xs hidden-sm">
      <h3>Didgeridoo les</h3>
      <div class="bulletlist">
        <ul>
          <li>1 - 25 personen</li>
          <li>Door zeer ervaren docent</li>
          <li>Zelf les gehad van verschillende aboriginals</li>
          <li>Lessen op originele en oefen didgeridoo's</li>
          <li>U oefent alle basis technieken in duidelijke oefeningen</li>
        </ul>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="didjeridu-paragraph">
          <p>De individuele didgeridoo les begint met het leren spelen van de grondtoon. Daarna leer je in stappen de circulaire ademhalingstechniek. Dit wil zeggen dat je inademt door de neus en tegelijkertijd lucht uitperst met je wangen door de mond. Hierdoor kun je wel een uur achter elkaar doorblazen zonder dat je de toon onderbreekt.

          Wanneer je dit beheerst leer je accenten met de stem, de wangen, de tong en de adem te maken. Deze accenten in combinatie met de circulaire ademhaling gaan we toepassen in verschillende maatsoorten, namelijk: 2/4, 3/4, 4/4, 5/8, 7/8 en 8/8.

          Ook leren we door het gebruik van de stem het imiteren van verschillende dierengeluiden uit Australië, zoals: de dingo, de laughing kookaburra, de goanna, het sissen van de slang en het springen van de kangoeroe. Verder leer je een aboriginal story te spelen op de didgeridoo.

          Als je nog geen eigen instrument hebt leer je hoe je heel goedkoop een eigen instrument van pvc kunt maken. Didgeridoolessen duren een uur en worden gegeven bij mij thuis. Zie contact voor mijn gegevens en het maken van een afspraak.</p>
          <img src="http://res.cloudinary.com/do6jihcuc/image/upload/v1505161400/didjeridujan_yg89es.jpg" style="width:213px;height:320px;">
        </div>
      </div>
    </div>

    <h3>Didgeridoo workshop</h3>
    <p class="last-paragraph-didjeridu">Tijdens een didgeridoo workshop maak je in een groep kennis met de basisvaardigheden van de didgeridoo. Samen worden oefeningen gedaan, waarna ervaringen worden uitgewisseld. De inhoud is in beknopte vorm wat ook onder didgeridoo les vermeld staat. In grote lijnen komt dit neer op het aanleren van de grondtoon, het oefenen van de circulaire ademhaling en oa. het imiteren van verschillende Australische dierengeluiden, zoals de dingo, de laughing kookaburra en de goanna. We ronden de workshop af met een aboriginal song die we met allen tezamen uitvoeren op de didgeridoo.

    Een groepsgrootte van 10 á 15 deelnemers is goed werkzaam. Originele en oefendidgeridoo's kunnen gehuurd worden. Tijdsduur is afhankelijk van wat de groep wil. Tussen een half uur en anderhalf uur wordt vaak gedaan.
    </p>
</div>

<!-- MOBIEL!! -->

<div class="container hidden-md hidden-lg">
      <h3>Didgeridoo les</h3>
      <div class="bulletlist">
        <ul>
          <li>1 - 25 personen</li>
          <li>Door zeer ervaren docent</li>
          <li>Zelf les gehad van verschillende aboriginals</li>
          <li>Lessen op originele en oefen didgeridoo's</li>
          <li>U oefent alle basis technieken in duidelijke oefeningen</li>
        </ul>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <p>De individuele didgeridoo les begint met het leren spelen van de grondtoon. Daarna leer je in stappen de circulaire ademhalingstechniek. Dit wil zeggen dat je inademt door de neus en tegelijkertijd lucht uitperst met je wangen door de mond. Hierdoor kun je wel een uur achter elkaar doorblazen zonder dat je de toon onderbreekt.

          Wanneer je dit beheerst leer je accenten met de stem, de wangen, de tong en de adem te maken. Deze accenten in combinatie met de circulaire ademhaling gaan we toepassen in verschillende maatsoorten, namelijk: 2/4, 3/4, 4/4, 5/8, 7/8 en 8/8.

          Ook leren we door het gebruik van de stem het imiteren van verschillende dierengeluiden uit Australië, zoals: de dingo, de laughing kookaburra, de goanna, het sissen van de slang en het springen van de kangoeroe. Verder leer je een aboriginal story te spelen op de didgeridoo.

          Als je nog geen eigen instrument hebt leer je hoe je heel goedkoop een eigen instrument van pvc kunt maken. Didgeridoolessen duren een uur en worden gegeven bij mij thuis. Zie contact voor mijn gegevens en het maken van een afspraak.</p>
      </div>
    </div>

    <h3>Didgeridoo workshop</h3>
    <p class="last-paragraph-didjeridu">Tijdens een didgeridoo workshop maak je in een groep kennis met de basisvaardigheden van de didgeridoo. Samen worden oefeningen gedaan, waarna ervaringen worden uitgewisseld. De inhoud is in beknopte vorm wat ook onder didgeridoo les vermeld staat. In grote lijnen komt dit neer op het aanleren van de grondtoon, het oefenen van de circulaire ademhaling en oa. het imiteren van verschillende Australische dierengeluiden, zoals de dingo, de laughing kookaburra en de goanna. We ronden de workshop af met een aboriginal song die we met allen tezamen uitvoeren op de didgeridoo.

    Een groepsgrootte van 10 á 15 deelnemers is goed werkzaam. Originele en oefendidgeridoo's kunnen gehuurd worden. Tijdsduur is afhankelijk van wat de groep wil. Tussen een half uur en anderhalf uur wordt vaak gedaan.
    </p>
</div>

app/views/pages/home.html.erb
 <div class="banner" style="background-image: url('http://res.cloudinary.com/do6jihcuc/image/upload/v1504534831/dirigent_vjywqu.jpg');">
  <div class="banner-content">
    <h2>Jan Terpstra</h2>
    <h1>Dirigent, piano lessen, didgeridoo lessen & workshops</h1>
  </div>
</div>


<div class="wrapper-grey">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-offset-4 col-sm-4">
          <div class="banner-content-mobile hidden-md hidden-lg">
            <h2>Jan Terpstra</h2>
            <h1>Dirigent, piano lessen, didgeridoo lessen & workshops</h1>
          </div>
          <div class="information-row">
          <p>In 2012 was ik dirigent in de laatste aflevering van de televisie serie: Moeder, ik wil bij de Revue. Deze is destijds bij de publieke omroep uitgezonden. Voor een televisie serie bij de publieke omroep had Moeder, ik wil bij de Revue onwaarschijnlijk hoge kijkcijfers. Dit had tot gevolg dat Joop van den Ende Theaterproducties dit heeft opgepakt en er nu een Musical van draait.</p>
          </div>
        </div>
      </div>
  </div>
</div>

<div class="wrapper-white">
  <div class="container">
    <div class="row">
      <div class="information">
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <h3>Koordirigent</h3>
            <img src="http://res.cloudinary.com/do6jihcuc/image/upload/v1504531150/Jan_oingoh.jpg" style="width:200px;height:200px;">
            <ul>
              <li>Enthousiaste, bevlogen dirigent</li>
              <li>Duidelijke, gestructureerde en boeiende repetities</li>
              <li>Afwisselend repetoire</li>
              <li>Altijd op zoek naar muzikale uitdaging</li>
            </ul>
            <%= link_to "Meer", koor_path, :class =>"btn-card"  %>
            <%= link_to "Agenda", agenda_path, :class =>"btn-agenda"  %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <h3>Pianoles</h3>
            <img src="http://res.cloudinary.com/do6jihcuc/image/upload/v1504540863/piano_Cropped_xywvnv.jpg" style="width:200px;height:200px;">
            <ul>
              <li>Betrokken en op de leerling afgestemd</li>
              <li>qua tempo en muzikale voorkeur</li>
              <li>van bv. Adele tot Mozart,</li>
              <li>In voor iedereen begrijpelijke lessen </li>
              <li class="last-li"></li>
            </ul>
            <%= link_to "Meer", piano_path, :class =>"btn-card"  %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <h3>Didgeridoo</h3>
            <img src="http://res.cloudinary.com/do6jihcuc/image/upload/v1504541179/didjeridu_soivw9.jpg" style="width:200px;height:200px;">
           <ul>
             <li>Traditioneel blaasinstrument</li>
             <li>Van de Aboriginals uit Australië</li>
             <li>Gemaakt van eucalyptushout</li>
             <li>Uitgehold door termieten</li>
             <li class="last-li"></li>
           </ul>
            <%= link_to "Meer", didjeridu_path, :class =>"btn-card"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/piano.html.erb
<div class="container hidden-xs hidden-sm">
  <h3>Pianoles</h3>
  <div class="bulletlist">
    <ul>
      <li>Individuele lessen</li>
      <li>Door zeer ervaren, gediplomeerd docent</li>
      <li>Ruime repertoire keuze</li>
      <li>Ontspannen lessfeer</li>
      <li>Duidelijke, gerichte oefeningen</li>
    </ul>
  </div>
  <div class="piano-box">
    <p>
    De pianoles is bedoeld voor jong en oud. Men begint met eenvoudige oefeningen om zowel de noten als de vingers te leren gebruiken. Op speelse wijze groeit het naar een steeds hoger niveau. Kinderen kunnen dan, als ze dat leuk vinden, over stappen op het leren van de nieuwste popliedjes. Hierbij leren ze zichzelf te begeleiden in akkoorden.
    <br>
    <p class="link">
    <%= link_to "Sophie's optreden", "https://www.youtube.com/watch?v=2ObfsTknMxA&feature=youtu.be", target: "_blank" %>
    </p>
    </p>
    <img src="http://res.cloudinary.com/do6jihcuc/image/upload/v1506009199/music_jpnnvm.png" style="width:315px;height:177px;">
    </div>
    <p class="last-paragraph">
    Volwassenen kunnen, afhankelijk van hun voorkeur, verder gaan met klassieke muziek. Andersom is voor beiden ook mogelijk natuurlijk. De lessen zijn wekelijks op alle dagen dat de lagere scholen ook les hebben. Iedere week een half uur les en tijdens de schoolvakanties dus vrij. Het is ook mogelijk om losse lessen af te spreken. Voor een gratis proefles klik hier. Voor media klik hier.</p>

    <p class="paragraph-bold">Voor een gratis pianoles, stuur mij een berichtje! Ga naar <%= link_to "Contact", new_contact_path %>.</p>
</div>

<div class="container hidden-md hidden-lg">
  <h3>Pianoles</h3>
  <div class="bulletlist">
    <ul>
      <li>Individuele lessen</li>
      <li>Door zeer ervaren, gediplomeerd docent</li>
      <li>Ruime repertoire keuze</li>
      <li>Ontspannen lessfeer</li>
      <li>Duidelijke, gerichte oefeningen</li>
    </ul>
  </div>
    <p>
    De pianoles is bedoeld voor jong en oud. Men begint met eenvoudige oefeningen om zowel de noten als de vingers te leren gebruiken. Op speelse wijze groeit het naar een steeds hoger niveau. Kinderen kunnen dan, als ze dat leuk vinden, over stappen op het leren van de nieuwste popliedjes. Hierbij leren ze zichzelf te begeleiden in akkoorden.
    <br>
    </p>
    <p>
    Volwassenen kunnen, afhankelijk van hun voorkeur, verder gaan met klassieke muziek. Andersom is voor beiden ook mogelijk natuurlijk. De lessen zijn wekelijks op alle dagen dat de lagere scholen ook les hebben. Iedere week een half uur les en tijdens de schoolvakanties dus vrij. Het is ook mogelijk om losse lessen af te spreken. Voor een gratis proefles klik hier. Voor media klik hier.</p>

    <p class="paragraph-bold">Voor een gratis pianoles, stuur mij een berichtje! Ga naar <%= link_to "Contact", new_contact_path %>.</p>
</div>

app/views/shared/_footer.html.erb
<div class="footer hidden-xs hidden-sm">
  <div class="footer-content">

      <div class="footer-details">
      <ul>Pastoor Gillisstraat 114</ul>
      <ul>5121 CG</ul>
      <ul>Rijen</ul>
    </div>

    <div class="footer-details">
      <ul>+31 639777370</ul>
      <ul>info@didjeridu.nl</ul>
      <ul>KVK: 18058320</ul>
      <ul>t.n.v. Terpstra Didjeridu's</ul>
    </div>

    <div class="footer-icons">
    <p>U vindt mij ook op: </p>
      <%= link_to "<i class='fa fa-facebook' aria-hidden='true'></i>".html_safe, "https://www.facebook.com/terpstramusic/", target: :_blank %>
      <%= link_to "<i class='fa fa-soundcloud' aria-hidden='true'></i>".html_safe, "https://soundcloud.com/jan-terpstra-1", target: :_blank %>
      <%= link_to "<i class='fa fa-linkedin' aria-hidden='true'></i>".html_safe, "https://www.linkedin.com/in/jan-terpstra-84495213/", target: :_blank %>
      <%= link_to "<i class='fa fa-youtube' aria-hidden='true'></i>".html_safe, "https://www.youtube.com/user/terpstramusic", target: :_blank %>
    </div>
  </div>
</div>

<!-- mobile only -->
<div class="footer hidden-md hidden-lg">
    <div class="footer-details-mobile">

     <div class="footer-icons">
        <p>U vindt mij ook op: </p>
          <%= link_to "<i class='fa fa-facebook' aria-hidden='true'></i>".html_safe, "https://www.facebook.com/terpstramusic/", target: :_blank %>
          <%= link_to "<i class='fa fa-soundcloud' aria-hidden='true'></i>".html_safe, "https://soundcloud.com/jan-terpstra-1", target: :_blank %>
          <%= link_to "<i class='fa fa-linkedin' aria-hidden='true'></i>".html_safe, "https://www.linkedin.com/in/jan-terpstra-84495213/", target: :_blank %>
          <%= link_to "<i class='fa fa-youtube' aria-hidden='true'></i>".html_safe, "https://www.youtube.com/user/terpstramusic", target: :_blank %>
      </div>
    </div>
    <div class="footer-details-mobile">
      <ul><b>Contactgegevens:</b></ul>
      <ul>Pastoor Gillisstraat 114</ul>
      <ul>5121 CG</ul>
      <ul>Rijen</ul>
    </div>

       <div class="footer-details-mobile">
      <ul>+31 639777370</ul>
      <ul>info@didjeridu.nl</ul>
      <ul>KVK: 18058320</ul>
      <ul>t.n.v. Terpstra Didjeridu's</ul>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Terpstra Music", root_path, :class => "navbar-wagon-item navbar-wagon-link navbar-logo"  %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Koordirigent", koor_path, :class => "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Pianoles", piano_path, :class => "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Didgeridoo", didjeridu_path, :class => "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Concertagenda", agenda_path, :class => "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Contact", new_contact_path, :class => "navbar-wagon-item navbar-wagon-link" %>
  </div>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <li><%= link_to "Home", root_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Koordirigent", koor_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Pianoles", piano_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Didgeridoo", didjeridu_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Concertagenda", agenda_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Contact", new_contact_path, :class => "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>